### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by bumbeishvili** [bumbeishvili/claudia-globe-fvr#1]
# Milestone 1

Remaining issues
- [x] • Improve background
- [x] • Add automatic rotation
- [x] • Improve map quality
- [x] • Remove some text legends
- [x] • Smoothen intersection lines
- [ ] • Add bumping effect (Which will give us a small 3D surface illusion)
